- all_metrics.html.md.erb
- metrics/_routing.html.md.erb
Hi, 
This PR will list the metrics available for all routing components through firehose. Routing components include routing-api, tcp-emitter, tcp-router (both router-configurer and haproxy) and gorouter.
Regards
Shash
CF Routing Team
> Document metrics emitted by routing components

- metrics/_routing.html.md.erb
This PR modifies routing metric descriptions with the correct frequency each metric is emitted through the firehose.
https://www.pivotaltracker.com/story/show/123528571
@flawedmatrix && @crhino
> Update routing metrics with correct intervals

- cli-plugin.html.md.erb
- metrics/_routing.html.md.erb
Hi, 
This PR updates gorouter metrics that previously described "total number" to  lifetime or instantaneous. This appears to be the convention across other parts of docs.
Regards
@shashwathi
CF Routing Team
Tracker story: https://www.pivotaltracker.com/story/show/127935343
> Update Gorouter metrics to use  instantaneous or lifetime counters

- metrics/_doppler.html.md.erb
- metrics/_metron_agent.html.md.erb
The HttpStart and HttpStop envelope types have been unused and deprecated in loggregator
for a very long time.  We haven't been emitting them for quite a while, and we're not
even using them internally since November, 2015.  We're starting to remove all related
code, so it makes sense to drop them from the docs, as well.
In the process of dropping that code, we also removed the `MessageAggregator.uncategorizedEvents` because it seems mostly useless.  It'll just be a duplicate of metron's total sent messages minus `MessageAggregator.counterEventReceived`, since the `MessageAggregator` no longer does anything with `HttpStart` and `HttpStop` events.
[#126660411]
Signed-off-by: Sam Nelson <snelson@pivotal.io>
> Removes unused metrics

- metrics/_routing.html.md.erb
`total_routes` metric represents the current number of registered routes and
not lifetime number.
Track story: https://www.pivotaltracker.com/story/show/131559337
Regards
Shash && Swetha
CF Routing team
> Update the description for total_routes metric

- metrics/_routing.html.md.erb
This PR adds documentation for unregister messages being emitted from router.
[#138389413]
Signed-off-by: Shash Reddy <sreddy@pivotal.io>
CF Routing team
Shash && Edwin
> Add documentation for unregister msgs

- metrics/_routing.html.md.erb
This PR documents websocket metrics for gorouter. 
Tracker story: https://www.pivotaltracker.com/story/show/136745595
Signed-off-by: Charles Hansen <chansen@pivotal.io>
Signed-off-by: Swetha Repakula <srepaku@us.ibm.com>
Regards
Shash
> Add websocket metrics to docs

- metrics/_routing.html.md.erb
This PR adds metric documentation for route_lookup_time.
Story: https://www.pivotaltracker.com/story/show/137286921
Signed-off-by: Shash Reddy <sreddy@pivotal.io>
> Add route_lookup_time to gorouter metrics.

- log-ops-guide.html.md.erb
- `DopplerServer.listeners.receivedEnvelopes` no longer exists
- `doppler.ingress` is the same as "Number of envelopes"
[#165744546]
> Remove deprecated tag

- container-metrics.html.md.erb
Source:
https://github.com/cloudfoundry/diego-release/blob/develop/jobs/rep/spec#L137-L139
> Diego container metrics are by default emitted every 15 s

- container-metrics.html.md.erb
- The existing documentation could be read as implying that all container metrics were available on Loggregator V1 ContainerMetric envelopes
- This isn't correct, some newer container metrics are only available within separate envelopes
> Clarify where container metrics can be found

- app-log-rate-limits.html.md.erb
- container-metrics.html.md.erb
This PR is to update the docs to reflect the new feature replacing the beta log-rate-limit feature in lines to now be in bytes/second.
> Change log rate limit feature to bytes/second

- app-log-rate-limits.html.md.erb
This PR is to update the docs to reflect new behavior for the beta log-rate-limit feature.
Previously, Diego was placing logs into a buffer and releasing them in accordance with the log line limit that was set. 
If the limit is exceeded, logs would be delayed. If the buffer overflowed, logs would be dropped. The new behavior is to immediately output logs without placing them into a buffer.  When the limit is reached, logs are dropped. This change makes the timestamps of logs match when they were actually output by the app.
> Change how log line limits drop lines

- container-metrics.html.md.erb
With this release https://github.com/cloudfoundry/garden-runc-release/releases/tag/v1.38.0, CF is now able to emit container metrics for received- and transmitted bytes.
See also https://github.com/cloudfoundry/diego-logging-client/pull/82/files to see the new emitted metrics.
This PR adds documentation related to the new metrics which should be published to https://docs.cloudfoundry.org/loggregator/container-metrics.html.
> Add container network metrics documentation

- data-sources.html.md.erb
This documentation of envelope types exists already in the [loggregator-api README](https://github.com/cloudfoundry/loggregator-api#v2-envelope-types). Adding it to the main documentation to make it easier to find and clear up any confusion.
> Document envelope types

- opentelemetry.html.md.erb
Asking the otel-collector binary directly which exporters are present is preferred to reviewing the distribution config.
> Remove reference to otel distribution config (5.0)

- opentelemetry.html.md.erb
Asking the otel-collector binary directly which exporters are present is preferred to reviewing the distribution config.
> Remove reference to otel distribution config

- container-metrics.html.md.erb
https://github.com/cloudfoundry/cf-deployment/pull/1164 added the new
`cpu_entitlement` container metric and deprecated and removed by default
the old `absolute_entitlement` and `absolute_usage` metrics.
This PR documents the new container metric based on my understanding of the relevant PRs.
> fix(container-metrics): Document `cpu_entitlement`

- container-metrics.html.md.erb
Removes outdated instructions for the CPU Entitlement plugin.
CAPI now exposes a `cpu_entitlement` metric in place of the `absolute_entitlement` and `absolute_usage` metrics. These will be captured in the cf CLI soon, but in the meantime the CPU Entitlement plugin should no longer be the go-to method for retrieving CPU Entitlement for apps.
> Removes information about cpu entitlement plugin (6.0)

- container-metrics.html.md.erb
Removes outdated instructions for the CPU Entitlement plugin.
CAPI now exposes a `cpu_entitlement` metric in place of the `absolute_entitlement` and `absolute_usage` metrics. These will be captured in the cf CLI soon, but in the meantime the CPU Entitlement plugin should no longer be the go-to method for retrieving CPU Entitlement for apps.
> Removes information about cpu entitlement plugin

- app-log-rate-limits.html.md.erb
- Clarify that log rate limits can be specified on tasks as well as apps
- Remove unused reference to log-cache plugin from firehose plug-in example
> Update log rate limiting docs
